### ISSUE TITLE
building command is not working.

### ISSUE THREAD

**Issue by rohitjaiswal** [DarkNess-reDefined/manifest#5]
mka darkness   is not working....

 make darkness worked now!

**Comment by DarkKnight6499** [comment]
. build/env*
lunch dnd_device-buildtype
mka darkness .
Its working !

**Comment by BRoy98** [comment]
@rohitjaiswal Lololololol 😂😂

**Comment by TheDarkStrix** [comment]
Wow

**Comment by AKabhishek** [comment]
Lol
